FROM centos:latest 
MAINTAINER Jim Perrin <jperrin@centos.org> 

ENV container=docker
RUN yum -y update && yum clean all
RUN yum -y install httpd
RUN systemctl enable httpd.service

VOLUME ["/run", "/tmp", "/sys/fs/cgroup"]
CMD ["/usr/sbin/init"]
